### PR TITLE
Support IntelliJ 2021.3

### PR DESCRIPTION
**Pull request by AdemJensen**
Modified versions of dependency IntelliJ Plugin to 2021.3

### CODE REVIEW

**Comment by gaydenko** [comment]
https://github.com/fkorotkov/intellij-thrift/pull/122

**Review by fkorotkov — APPROVED** [review]

**Comment by fkorotkov** [comment]
Just release `1.11.0` which should be available soon after JetBrains Marketplace review.

**Comment by jake-klingler** [comment]
> Just release `1.11.0` which should be available soon after JetBrains Marketplace review.

@fkorotkov - thanks for your work on this plugin!  `1.11.0` was released 12 days ago but it's still not live on the marketplace. JB review normally only takes a few days, right? Are we sure the new version got submitted for review? Anything we can do to help expedite the review process?

**Comment by gaydenko** [comment]
Are there chances to find the update in marketplace? :) It seems nobody understands  the situation...

**Comment by calvinit** [comment]
It seems that there is no follow-up to this matter. Can any brother help to look at the review progress of the Jetbrains Marketplace?

**Comment by aosorio1** [comment]
As of February 6 this hasn't be released in the Marketplace.

**Comment by fkorotkov** [comment]
Only saw @aosorio1's ping. Sorry about that! 1.11.0 release failed because of Bintray issue. Release 1.11.1 and verified it's [available in Marketplace](https://plugins.jetbrains.com/plugin/7331-thrift-support/versions/stable/156718).

**Pull request merged**
