### PR TITLE
WIP - Support apps other than IntelliJ

### PR DESCRIPTION
**Pull request by honorabel**
Perhaps there are issues with this, but it seems this project is not far off at all from supporting the other jetbrains apps.  

I built this using IntelliJ IDEA CE IC-171.3780.107 SDK.  The section of commented code was necessary to get it to compile.  I'm sure there is a correct way to do it.  

With the simple inclusion of the `<depends>` tags, I am able to run the plugin successfully in PyCharm.

### CODE REVIEW

**Comment by honorabel** [comment]
I'll note that attempting to build the plugin against the actual pycharm SDK does expose all the dependencies in much more clarity, and there are certainly bugs when using the plugin in PyCharm (e.g. the structureView will throw an error as it hits a ClassDefNotFound error).  

I am not very experienced with the jetbrains plugin API, but am curious how much work it might be to disentangle the Intellij-specific api calls from the generic ones.

**Comment by honorabel** [comment]
My latest changes remove all components that appear dependent on intellij-only components.  With those changes, the plugin appears to function pretty successfully in PyCharm.

**Comment by fkorotkov** [comment]
Fixed in https://github.com/fkorotkov/intellij-thrift/commit/705a2cde99a3858f2b3f49d91db0ebe53bac1adc

Verified with PyCharm CE

**Comment by honorabel** [comment]
Awesome! Thanks for the great work!

**Comment by honorabel** [comment]
Do you plan to create a new release to include those commits?

**Comment by fkorotkov** [comment]
@honorabel released `0.9.7` like 30 minutes ago. So should be available to everyone shortly 🙌

**Pull request closed without merging**
